apiVersion: v1  # API version used for the Service resource
kind: Service  # Declares this resource as a Service

metadata:
  name: nginx-svc  # Name of the Service
  namespace: nginx-ns  # Namespace in which the Service is created

spec:
  selector:
    app: nginx  # This Service will route traffic to Pods labeled with 'app: nginx'
  
  ports:
    - protocol: TCP      # Protocol used for communication (TCP in this case)
      port: 82           # Port on which the Service will be exposed inside the cluster
      targetPort: 80     # Port on the Pod/container that will receive the traffic
